{{- if and (eq .Values.hpa.enabled true) ( eq .Values.canary.enabled "false") }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.service.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.service.name }}
  minReplicas: {{ .Values.hpa.min_number }}
  maxReplicas: {{ .Values.hpa.max_number }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpuaverageUtilization }}
{{- if (eq .Values.hpa.mem_enabled true)}}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.memaverageUtilization }}
{{- end }}
{{ end }}
