{{- if eq .Values.canary.enabled "false" }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }}
  labels:
    metrics: "{{ .Values.prometheus.scrape }}"
    scrapeInterval: "{{ .Values.prometheus.time }}"
    app: {{ .Values.service.name }}
{{- if eq .Values.service.prome_monitor_jvm true }}
  annotations:
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/spring: "true"
    prometheus.io/path: "/actuator/prometheus"
{{- end }}
spec:
{{- if eq .Values.service.svc_types "clusterIP" }}
  type: ClusterIP
{{- else if eq .Values.service.svc_types "NodePort" }}
  type: NodePort
{{- end }}
  ports:
{{- if eq .Values.service.judge_php.enable "true" }}
  - port: 80
    targetPort: 80
{{- else if or ( eq .Values.cluster "clotho-kr-prod" ) (eq .Values.cluster "clotho-us-prod")}}
  - port: 80
    targetPort: {{ .Values.service.port }}
{{- else }}
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
{{- end }}
{{- if eq .Values.service.svc_types "NodePort" }}
    nodePort: {{ .Values.service.port }}
{{- end }}
    protocol: TCP
    name: serverport
  selector:
    app: {{ .Values.service.name }}
{{- end }}
