apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
  labels:
    name: prometheus
spec:
  capacity:
    storage: 1.5Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /k8s-local-pv/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: k8s-storage
          operator: In
          values:
          - local-pv
